### ISSUE TITLE
Quantidade de Números da Aposta

### ISSUE THREAD

**Issue by heitor19oliveira** [arthurtomas/mega-sena#1]
A função de aposta está com 4 números, mas são 6.

**Comment by arthurtomas** [comment]
Verdade @heitor19oliveira 
Minha ideia analisando o código é criar uma constante global chamada N_MAX e adiciona-la à função aposta(), substituindo o range máximo e de maneira semelhante na função resultado() substituindo o tamanho da lista.

**Comment by heitor19oliveira** [comment]
Genial.

**Comment by arthurtomas** [comment]
`https://github.com/arthurtomas/mega-sena/commit/1cbb8d65753efb2d47c1c4cb8da53c9f1c492e22`
Variável N_MAX criada.

**Comment by arthurtomas** [comment]
[Variável N_MAX adicionada](https://github.com/arthurtomas/mega-sena/commit/1cbb8d65753efb2d47c1c4cb8da53c9f1c492e22)

**Comment by arthurtomas** [comment]
101616d teste

**Comment by arthurtomas** [comment]
Constante N_MAX adicionada, como pode ser visto no commit abaixo.
101616d

**Comment by arthurtomas** [comment]
Eu decidi manter a constante N_MAX com o valor = 4.
Como pode-se perceber usando a fórmula de Combinação Simples, quando N_MAX = 4, temos 487 635 possiblididades de resultado, o que mantém um tempo razoável de execução do programa, porém quando definimos N_MAX = 6, o número de possibilidades de resultado passa a ser de 50 063 860(Possibilidade real de resultados da Mega Sena), o que torna a execução do programa muito demorada, o que não é o intuito desse projeto.

**Comment by heitor19oliveira** [comment]
Nice Job
